### ISSUE TITLE
does this plugin work with 2.5.2?

### ISSUE THREAD

**Issue by rompic** [thorin/redmine_local_avatars#4]
the readme is rather unclear about this

**Comment by thorin** [comment]
There are no tests. 
As so, it might work and might also not work.
I cannot guarantee it since I'm don't have the free time to fully maintain this plugin.

Any correction to the documentation is welcome.

Thank you

**Comment by rompic** [comment]
first tests look promising.

kind regards,
Roman

**Comment by rompic** [comment]
any experience on 3.x?

**Comment by thorin** [comment]
Seems to work fine. 
But I haven't tested it yet on a production system.
